- name: RH username to login to the RH docker registry
  pause:
    prompt: "RH username"
  register: rh_username

- name: RH password to login to the RH docker registry
  pause:
    prompt: "RH password"
    echo: no
  register: rh_password

- name: Login to the RH docker registry
  shell: podman login -u {{ rh_username.user_input }} -p {{ rh_password.user_input }} {{ rh_docker_registry }}

- name: Prep containers parameters file
  template:
    src: containers-prepare-parameters.j2
    dest: /home/stack/containers-prepare-parameters.yaml

- name: Prep standalone parameters file
  template:
    src: standalone_parameters.j2
    dest: /home/stack/standalone_parameters.yaml

- name: Prep deployment script
  template:
    src: deploy.j2
    dest: /home/stack/deploy.sh

- name: Deploy AIO RHOSP
  shell: sh /home/stack/deploy.sh
  register: deploy_sh
