- name: Refresh the facts
  setup:

- name: RH username to login to the RH docker registry
  pause:
    prompt: "Enter RH username"
    echo: no
  register: rh_username
  tags:
    - deploy_aio_rhosp

- name: RH password to login to the RH docker registry
  pause:
    prompt: "Enter RH password"
    echo: no
  register: rh_password
  tags:
    - deploy_aio_rhosp

- name: Login to the RH docker registry
  shell: podman login -u {{ rh_username.user_input }} -p {{ rh_password.user_input }} {{ rh_docker_registry }}
  tags:
    - deploy_aio_rhosp

- name: Check if containers-prepare file exist
  stat:
    path: /home/stack/containers-prepare-parameters.yaml
  register: containers_prepare_file
  tags:
    - deploy_aio_rhosp

- name: Prep containers parameters file
  template:
    src: containers-prepare-parameters.j2
    dest: /home/stack/containers-prepare-parameters.yaml
  when: containers_prepare_file.stat.exists == False
  tags:
    - deploy_aio_rhosp

- name: Check if standalone_parameters file exist
  stat:
    path: /home/stack/standalone_parameters.yaml
  register: standalone_parameters_file
  tags:
    - deploy_aio_rhosp

- name: Prep standalone parameters file
  template:
    src: standalone_parameters.j2
    dest: /home/stack/standalone_parameters.yaml
  when: standalone_parameters_file.stat.exists == False
  tags:
    - deploy_aio_rhosp

- name: Check if deploy.sh file exist
  stat:
    path: /home/stack/deploy.sh
  register: deploy_sh_file
  tags:
    - deploy_aio_rhosp

- name: Prep deployment script
  template:
    src: deploy.j2
    dest: /home/stack/deploy.sh
  when: deploy_sh_file.stat.exists == False
  tags:
    - deploy_aio_rhosp

- name: Deploy AIO RHOSP
  shell: sh /home/stack/deploy.sh
  register: deploy_sh
  tags:
    - deploy_aio_rhosp

- name: Installation status
  stat:
    path: /home/stack/.config/openstack/clouds.yaml
  register: config_openstack_clouds_file
  tags:
    - deploy_aio_rhosp

- name: Installation debug
  debug:
    msg: "{{ deploy_sh }}"
  when: config_openstack_clouds_file.stat.exists == False
  tags:
    - deploy_aio_rhosp

- name: Refresh the facts
  setup:

- name: Deployment successful
  debug:
    msg:
      - Deployment successful!
      - The clouds.yaml file is at /home/stack/.config/openstack/clouds.yaml.
      - Use `export OS_CLOUD=standalone` before running the openstack command.
      - "Horizon dashboard URL: http://{{ hostvars[inventory_hostname].facter_networking.interfaces['br-ctlplane'].bindings[0].address }}"
  when: config_openstack_clouds_file.stat.exists
  tags:
    - deploy_aio_rhosp
