- name: gather facts on existing networks
  virt_net:
    command: facts
  register: virt_networks
  tags:
    - kvm
    - virt_pool

- name: Create network1
  virt_net:
    command: define
    name: "{{ network1_name | default('default') }}"
    xml: '{{ lookup("template", "templates/network1.j2") }}'
  tags:
    - kvm
    - virt_network
  when: virt_networks.ansible_facts.network1_name is not defined

- name: Create network2
  virt_net:
    command: define
    name: "{{ network2_name | default(osp) }}"
    xml: '{{ lookup("template", "templates/network2.j2") }}'
  tags:
    - kvm
    - virt_network
  when: virt_networks.ansible_facts.network2_name is not defined

- name: Autostart the network1
  virt_net:
    name: "{{ network1_name | default(default) }}"
    autostart: yes
    state: active
  tags:
    - kvm
    - virt_network

- name: Autostart the network2
  virt_net:
    name: "{{ network2_name | default(osp) }}"
    autostart: yes
    state: active
  tags:
    - kvm
    - virt_network
