- name: List networks
  virt_net:
    command: list_nets
  register: net_list
  tags:
  - deploy_vm

- name: Network output
  debug:
    msg: "{{ net_list }}"
  tags:
  - deploy_vm

- name: Create network1
  virt_net:
    command: define
    name: "{{ network1_name | default('osp_mgmt') }}"
    xml: '{{ lookup("template", "templates/network1.j2") }}'
  when: network1_name not in net_list.list_nets
  tags:
  - deploy_vm

- name: Create network2
  virt_net:
    command: define
    name: "{{ network2_name | default(osp) }}"
    xml: '{{ lookup("template", "templates/network2.j2") }}'
  when:  network2_name not in net_list.list_nets
  tags:
  - deploy_vm

- name: Autostart the network1
  virt_net:
    name: "{{ network1_name | default(default) }}"
    autostart: yes
    state: active
  tags:
  - deploy_vm

- name: Autostart the network2
  virt_net:
    name: "{{ network2_name | default(osp) }}"
    autostart: yes
    state: active
  tags:
  - deploy_vm
