- name: Install virtualization packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ virt_packages }}"
  tags:
  - deploy_vm

- name: Enable service libvirt, and start if not started
  service:
    name: libvirtd
    enabled: yes
    state: started
  tags:
  - deploy_vm
  - list_network
  - check_service
