- name: Install virtualization packages
  package:
    name: "{{ item }}"
    state: present
  tags:
    - packages
    - kvm
  with_items:
    "{{ virt_packages }}"

- name: Enable service libvirt, and start if not started
  service:
    name: libvirtd
    enabled: yes
    state: started
  tags:
    - kvm
