- name: Create workaround directory
  file:
    path: /opt/workaround
    state: directory
  tags:
    - rhel8_qcow2_workaround

- name: Download libguestfs binary appliance
  get_url:
    url: https://download.libguestfs.org/binaries/appliance/appliance-1.40.1.tar.xz
    dest: /opt/workaround
  tags:
    - rhel8_qcow2_workaround

- name: Extract the appliance
  unarchive:
    src: /opt/workaround/appliance-1.40.1.tar.xz
    dest: "{{ ansible_env.HOME }}"
  tags:
    - rhel8_qcow2_workaround
