- name: RHEL8-Workaround-libguestfs - Create workaround directory
  file:
    path: /opt/workaround
    state: directory
  tags:
    - deploy_vm

- name: RHEL8-Workaround-libguestfs - Download libguestfs binary appliance
  get_url:
    url: https://download.libguestfs.org/binaries/appliance/appliance-1.40.1.tar.xz
    dest: /opt/workaround
  tags:
    - deploy_vm

- name: RHEL8-Workaround-libguestfs - Extract the appliance
  unarchive:
    src: /opt/workaround/appliance-1.40.1.tar.xz
    dest: /opt/workaround/
    creates: /opt/workaround/appliance
  tags:
    - deploy_vm
